name: Deploy to Azure Static Web Apps

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

  jobs:
    build_and_deploy_job:
      runs-on: ubuntu-latest
      name: Build and Deploy Job
      steps:
        - uses: actions/checkout@v3
          with:
            submodules: true
        - name: Build And Deploy
          id: builddeploy
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
            repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
            action: "upload"
            ###### Repository/Build Configurations ######
            app_location: "src" # App source code path relative to repository root
            output_location: "public" # Built app content directory, relative to app_location - optional
            ###### End of Repository/Build Configurations ######
